/* Admin panel */
P.guard('admin','Admin Panel – sign in',function(sess){
const {$,$$,esc,inr,fdate,stars,avatar,typeLabel,pill,prop,owner,student,img,toast,modal,confirmBox}=P;
const NAV=[['dashboard','📊','Dashboard'],['owners','🏢','Owners'],['properties','🏠','Properties'],['students','🎓','Students'],['bookings','📅','Bookings'],['reviews','⭐','Reviews'],['feedback','💬','Feedback'],['earnings','💰','Earnings']];
const rate=()=>+P.db.settings.commission_rate||5;
function shell(){
  $('#app').innerHTML=`<nav class="navbar-custom" style="display:flex;align-items:center;gap:12px;position:fixed;top:0;left:0;right:0;height:70px;padding:0 16px;z-index:1030;color:#fff"><button class="menu-btn" id="mb">☰</button><a class="navbar-brand" href="admin.html" style="color:#fff;text-decoration:none;font-weight:700;font-size:1.4rem">Stay<span style="color:#ffd700">Smart</span> <small style="font-size:.7rem;opacity:.85">Admin</small></a><div class="nav-right"><a class="btn btn-sm btn-warning" href="index.html">Student site</a><button class="btn btn-sm btn-dark" id="rs">Reset demo</button><button class="btn btn-sm btn-danger" id="lo" style="background:#7a1420">Logout</button></div></nav>
  <aside class="admin-sidebar" id="sb"><div style="padding:12px 0" id="sm"></div></aside><main class="content" id="view"></main>`;
  $('#mb').onclick=()=>$('#sb').classList.toggle('show');$('#lo').onclick=()=>{P.logout();location.href='index.html'};
  $('#rs').onclick=()=>confirmBox('Reset all demo data back to the original seed?',()=>P.reset());}
const pendingCounts=()=>({owners:P.db.owners.filter(o=>o.status==='pending').length,reviews:P.db.reviews.filter(r=>r.status==='pending').length,feedback:P.db.feedback.filter(f=>f.status==='pending').length,bookings:P.db.bookings.filter(b=>b.status==='pending').length});
function menu(pg){const c=pendingCounts();$('#sm').innerHTML=NAV.map(([k,i,l])=>`<a class="nav-link ${k===pg?'active':''}" href="#${k}" style="display:flex;align-items:center;gap:10px;text-decoration:none"><span>${i}</span>${l}${c[k]?`<span class="badge bg-danger" style="margin-left:auto">${c[k]}</span>`:''}</a>`).join('');$('#sb').classList.remove('show')}
const T=(t,r)=>`<div class="d-flex between align-center flex-wrap gap-2 mb-3"><h3 class="mb-0">${t}</h3>${r||''}</div>`;
const tbl=(h,rows)=>`<div class="card"><div class="table-wrap"><table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${h.length}" class="empty-soft">Nothing to show.</td></tr>`}</tbody></table></div></div>`;
const earnTotal=t=>P.db.earnings.filter(e=>!t||e.type===t).reduce((a,e)=>a+e.amount,0);

function dashboard(){const d=P.db,c=pendingCounts();
  const S=[['🏢',d.owners.length,'Owners','owners'],['🏠',d.properties.length,'Properties','properties'],['🎓',d.students.length,'Students','students'],['📅',d.bookings.length,'Bookings','bookings'],['⏳',c.owners,'Owners awaiting approval','owners'],['📝',c.reviews,'Reviews to moderate','reviews'],['💬',c.feedback,'Pending feedback','feedback'],['💰',inr(earnTotal()),'Platform revenue','earnings']];
  $('#view').innerHTML=T('Admin Dashboard')+`<div class="grid cols-4 mb-4">${S.map(([i,v,l,g])=>`<div class="stat-card chip-link" data-g="${g}"><div style="font-size:2rem">${i}</div><div class="v">${v}</div><div class="text-muted small">${l}</div></div>`).join('')}</div>
  <div class="grid cols-2"><div class="card card-body"><h5>Latest bookings</h5>${d.bookings.slice().sort((a,b)=>b.id-a.id).slice(0,5).map(b=>`<div class="d-flex between align-center mb-2"><div><b>${esc((student(b.studentId)||{}).name)}</b><div class="small text-muted">${esc((prop(b.propertyId)||{}).title)}</div></div>${pill(b.status)}</div>`).join('')}</div>
  <div class="card card-body"><h5>Owner approvals</h5>${d.owners.slice(0,6).map(o=>`<div class="d-flex between align-center mb-2"><span>${esc(o.name)}</span>${pill(o.status)}</div>`).join('')}</div></div>`;
  $$('[data-g]').forEach(x=>x.onclick=()=>location.hash='#'+x.dataset.g)}

function owners(){const l=P.db.owners;
  $('#view').innerHTML=T('Owners / Landlords')+tbl(['Owner','Contact','City','Properties','Status','Actions'],l.map(o=>`<tr><td><div class="d-flex gap-2 align-center">${avatar(o.name,'#b02a37')}<div><b>${esc(o.name)}</b><div class="small text-muted">${esc(o.company||'')}</div></div></div></td><td class="small">${esc(o.email)}<br>${esc(o.phone||'')}</td><td>${esc(o.city||'—')}</td><td>${P.db.properties.filter(p=>p.ownerId==o.id).length}</td><td>${pill(o.status)}</td>
  <td>${o.status!=='approved'?`<button class="btn btn-success btn-sm" data-s="approved" data-id="${o.id}">Approve</button> `:''}${o.status!=='rejected'?`<button class="btn btn-danger btn-sm" data-s="rejected" data-id="${o.id}">Reject</button>`:''}</td></tr>`));
  $$('[data-s]').forEach(b=>b.onclick=()=>{const o=owner(b.dataset.id);o.status=b.dataset.s;P.notify(o.id,'Account '+o.status,'Your owner account was '+o.status+' by the admin.','system');P.save();toast(o.name+' '+o.status);route()})}
function properties(){const l=P.db.properties;
  $('#view').innerHTML=T('Properties')+tbl(['Property','Owner','City','Rent','Type','Status','Actions'],l.map(p=>`<tr><td><div class="d-flex gap-2 align-center"><img class="thumb-sm" src="${esc(img(p))}" alt=""><div><b>${esc(p.title)}</b><div class="small text-muted">#${p.id}</div></div></div></td><td>${esc((owner(p.ownerId)||{}).name||'—')}</td><td>${esc(p.city)}</td><td>${inr(p.rent)}</td><td>${esc(typeLabel(p.type))}</td><td>${pill(p.status==='available'?'approved':'pending').replace(/Approved|Pending/,p.status==='available'?'Available':p.status==='occupied'?'Occupied':'Unavailable')}</td>
  <td><button class="btn btn-sm btn-warning" data-f="${p.id}">${p.featured?'★ Unfeature':'☆ Feature'}</button> <button class="btn btn-sm btn-danger" data-d="${p.id}">Delete</button></td></tr>`));
  $$('[data-f]').forEach(b=>b.onclick=()=>{const p=prop(b.dataset.f);p.featured=!p.featured;P.save();toast(p.featured?'Marked featured':'Removed from featured');properties()});
  $$('[data-d]').forEach(b=>b.onclick=()=>confirmBox('Delete this listing?',()=>{P.db.properties=P.db.properties.filter(p=>p.id!=b.dataset.d);P.save();toast('Listing deleted');properties();menu('properties')}))}
function students(){const l=P.db.students;
  $('#view').innerHTML=T('Students')+tbl(['Student','Email','Phone','Joined','Bookings','Status','Action'],l.map(s=>`<tr><td><div class="d-flex gap-2 align-center">${avatar(s.name,'#0066CC')}<b>${esc(s.name)}</b></div></td><td class="small">${esc(s.email)}</td><td>${esc(s.phone||'—')}</td><td>${fdate(s.joined)}</td><td>${P.db.bookings.filter(b=>b.studentId==s.id).length}</td><td>${s.active?'<span class="badge bg-success">Active</span>':'<span class="badge bg-secondary">Suspended</span>'}</td><td><button class="btn btn-sm ${s.active?'btn-outline-danger':'btn-success'}" data-t="${s.id}">${s.active?'Suspend':'Activate'}</button></td></tr>`));
  $$('[data-t]').forEach(b=>b.onclick=()=>{const s=student(b.dataset.t);s.active=!s.active;P.save();toast(s.name+(s.active?' activated':' suspended'));students()})}
let bf='all';
function bookings(){const all=P.db.bookings.slice().sort((a,b)=>b.id-a.id),l=bf==='all'?all:all.filter(b=>b.status===bf);
  $('#view').innerHTML=T('All Bookings')+`<div class="tabs-row mb-3">${['all','pending','approved','active','completed','rejected','cancelled'].map(t=>`<button class="btn btn-sm ${t===bf?'btn-primary':''}" data-t="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>`+tbl(['#','Student','Property','Owner','Dates','Total','Payment','Status'],l.map(b=>`<tr><td>${b.id}</td><td>${esc((student(b.studentId)||{}).name)}</td><td>${esc((prop(b.propertyId)||{}).title)}</td><td>${esc((owner(b.ownerId)||{}).name)}</td><td class="small">${fdate(b.start)}<br>→ ${fdate(b.end)}</td><td>${inr(b.total)}</td><td>${esc(b.payment)}</td><td>${pill(b.status)}</td></tr>`));
  $$('[data-t]').forEach(b=>b.onclick=()=>{bf=b.dataset.t;bookings()})}
function reviews(){const l=P.db.reviews.slice().sort((a,b)=>b.id-a.id);
  $('#view').innerHTML=T('Review Moderation')+tbl(['Property','Student','Rating','Review','Status','Actions'],l.map(r=>`<tr><td>${esc((prop(r.propertyId)||{}).title)}</td><td>${esc((student(r.studentId)||{}).name)}</td><td>${stars(r.rating)}</td><td style="max-width:280px"><b>${esc(r.title)}</b><div class="small">${esc(r.text)}</div></td><td>${pill(r.status)}</td><td>${r.status!=='approved'?`<button class="btn btn-sm btn-success" data-s="approved" data-id="${r.id}">Approve</button> `:''}${r.status!=='rejected'?`<button class="btn btn-sm btn-danger" data-s="rejected" data-id="${r.id}">Reject</button>`:''}</td></tr>`));
  $$('[data-s]').forEach(b=>b.onclick=()=>{P.db.reviews.find(r=>r.id==b.dataset.id).status=b.dataset.s;P.save();toast('Review '+b.dataset.s);reviews();menu('reviews')})}
function feedback(){const l=P.db.feedback.slice().sort((a,b)=>b.id-a.id);
  $('#view').innerHTML=T('Platform Feedback')+`<div class="grid cols-2">${l.map(f=>`<div class="card card-body"><div class="d-flex between"><b>${esc(f.title)}</b>${pill(f.status)}</div>${stars(f.rating)}<p class="small mt-2 mb-1">${esc(f.text)}</p>${f.suggestions?`<div class="small text-muted">💡 ${esc(f.suggestions)}</div>`:''}<div class="small text-muted mt-1">${esc(f.name)} · ${f.role==='landlord'?'Owner':'Student'} · ${fdate(f.date)}</div><div class="mt-2 d-flex gap-2">${f.status==='pending'?`<button class="btn btn-sm btn-success" data-s="reviewed" data-id="${f.id}">Mark reviewed</button>`:''}${f.status!=='resolved'?`<button class="btn btn-sm btn-primary" data-s="resolved" data-id="${f.id}">Resolve</button>`:''}</div></div>`).join('')}</div>`;
  $$('[data-s]').forEach(b=>b.onclick=()=>{P.db.feedback.find(f=>f.id==b.dataset.id).status=b.dataset.s;P.save();toast('Feedback '+b.dataset.s);feedback();menu('feedback')})}
function earnings(){const E=P.db.earnings,st=earnTotal('student_fee'),ld=earnTotal('landlord_service_fee');
  const mon={};E.forEach(e=>{const k=e.date.slice(0,7);mon[k]=mon[k]||{s:0,l:0};e.type==='student_fee'?mon[k].s+=e.amount:mon[k].l+=e.amount});
  const ks=Object.keys(mon).sort(),mx=Math.max(1,...ks.map(k=>mon[k].s+mon[k].l));
  const W=640,H=260,bw=Math.min(60,W/Math.max(ks.length,1)-20);
  const svg=`<svg viewBox="0 0 ${W} ${H}" style="width:100%;max-height:300px">${ks.map((k,i)=>{const x=40+i*(W-60)/Math.max(ks.length,1)+10,hs=mon[k].s/mx*190,hl=mon[k].l/mx*190;return `<rect x="${x}" y="${220-hl}" width="${bw}" height="${hl}" fill="#f0a500" rx="4"/><rect x="${x}" y="${220-hl-hs}" width="${bw}" height="${hs}" fill="#0f68c9" rx="4"/><text x="${x+bw/2}" y="240" font-size="11" text-anchor="middle" fill="#5f7188">${k}</text><text x="${x+bw/2}" y="${215-hl-hs}" font-size="11" text-anchor="middle" fill="#333">${inr(mon[k].s+mon[k].l)}</text>`}).join('')}</svg>`;
  $('#view').innerHTML=`<div class="earnings-hero mb-4"><h2 style="color:#fff">💰 Platform Earnings</h2><p class="earnings-hero-subtitle">Revenue from student confirmation fees and the ${rate()}% owner service commission.</p></div>
  <div class="grid cols-3 mb-4"><div class="earnings-summary-card card-body" style="background:linear-gradient(135deg,#0f68c9,#184c93)"><div class="earnings-icon">💵</div><h2>${inr(st+ld)}</h2><div>Total revenue</div></div><div class="earnings-summary-card card-body" style="background:linear-gradient(135deg,#198754,#0f7a36)"><div class="earnings-icon">🎓</div><h2>${inr(st)}</h2><div>Student fees</div></div><div class="earnings-summary-card card-body" style="background:linear-gradient(135deg,#f0a500,#c98400)"><div class="earnings-icon">🏢</div><h2>${inr(ld)}</h2><div>Owner service fees</div></div></div>
  <div class="chart-card card mb-4"><div class="card-header">Revenue by month</div><div class="card-body chart-wrap">${ks.length?svg:'<div class="empty-soft">No earnings yet.</div>'}<div class="chart-meta"><span class="chart-chip">🔵 Student fees</span><span class="chart-chip">🟠 Owner fees</span></div></div></div>
  <div class="payments-card card"><div class="card-header">Recent earning records</div>${tbl(['Date','Booking','Type','Amount'],E.slice().sort((a,b)=>b.id-a.id).map(e=>{const b=P.db.bookings.find(x=>x.id==e.bookingId)||{};return `<tr><td>${fdate(e.date)}</td><td>#${e.bookingId} · ${esc((prop(b.propertyId)||{}).title||'')}</td><td><span class="earning-badge ${e.type==='student_fee'?'student':'landlord'}">${e.type==='student_fee'?'Student fee':'Owner service fee'}</span></td><td class="amount-primary">${inr(e.amount)}</td></tr>`}))}</div>`}
const R={dashboard,owners,properties,students,bookings,reviews,feedback,earnings};
function route(){const k=(location.hash||'#dashboard').slice(1),pg=R[k]?k:'dashboard';menu(pg);R[pg]();window.scrollTo(0,0)}
shell();route();addEventListener('hashchange',route);
});
